#!/usr/bin/env bash
# fix-voice.sh — Diagnose and fix TURN/voice connectivity on the orblood server.
#
# Run on the server (as root):
#   sudo bash /opt/orblood/scripts/fix-voice.sh
#
# What it does:
#   1. Reads existing TURN credentials from /opt/orblood/server/.env
#      (or generates new ones if missing).
#   2. Detects the public IP automatically (multiple fallbacks).
#   3. Writes a clean /etc/turnserver.conf that matches the .env exactly.
#   4. Opens UFW firewall ports for STUN/TURN traffic.
#   5. Restarts coturn + the orblood backend.
#   6. Verifies coturn is listening + reachable.
#
# Re-runs are safe.

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/orblood}"
ENV_FILE="$INSTALL_DIR/server/.env"

say()  { printf '\n\033[1;36m== %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m!! %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m== %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31m!! %s\033[0m\n' "$*"; exit 1; }

[ "$(id -u)" = "0" ] || fail "Run me as root: sudo bash $0"
[ -f "$ENV_FILE" ] || fail "$ENV_FILE not found. Run install.sh first."

# ----- 1. Read existing config from .env -----
say "Reading TURN config from $ENV_FILE"
DOMAIN="$(awk -F= '/^PUBLIC_ORIGIN=/{print $2}' "$ENV_FILE" | sed -E 's|https?://||' | tr -d ' "'"'"'')"
TURN_USERNAME="$(awk -F= '/^TURN_USERNAME=/{print $2}' "$ENV_FILE" | tr -d ' "'"'"'')"
TURN_PASSWORD="$(awk -F= '/^TURN_PASSWORD=/{print $2}' "$ENV_FILE" | tr -d ' "'"'"'')"
# Legacy fallback to EXPRESSTURN_*
[ -z "$TURN_USERNAME" ] && TURN_USERNAME="$(awk -F= '/^EXPRESSTURN_USERNAME=/{print $2}' "$ENV_FILE" | tr -d ' "'"'"'')"
[ -z "$TURN_PASSWORD" ] && TURN_PASSWORD="$(awk -F= '/^EXPRESSTURN_PASSWORD=/{print $2}' "$ENV_FILE" | tr -d ' "'"'"'')"

[ -n "$DOMAIN" ]        || fail "PUBLIC_ORIGIN missing from .env"
[ -n "$TURN_USERNAME" ] || TURN_USERNAME="orblood"
[ -n "$TURN_PASSWORD" ] || TURN_PASSWORD="$(openssl rand -hex 16)"

echo "  Domain:       $DOMAIN"
echo "  TURN user:    $TURN_USERNAME"
echo "  TURN pass:    ${TURN_PASSWORD:0:8}..."

# ----- 2. Detect public IP -----
say "Detecting public IP"
EXTERNAL_IP="$(curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null \
  || curl -fsSL --max-time 5 https://ifconfig.me 2>/dev/null \
  || curl -fsSL --max-time 5 https://checkip.amazonaws.com 2>/dev/null \
  || curl -fsSL --max-time 5 https://api.myip.com 2>/dev/null | jq -r .ip 2>/dev/null \
  || ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' \
  || true)"
EXTERNAL_IP="$(echo "$EXTERNAL_IP" | tr -d '[:space:]')"

if [ -z "$EXTERNAL_IP" ]; then
  warn "Could not detect public IP automatically."
  read -rp "Enter the server's public IP manually: " EXTERNAL_IP
fi
[ -n "$EXTERNAL_IP" ] || fail "EXTERNAL_IP required."
echo "  Public IP:    $EXTERNAL_IP"

# ----- 3. Update the env file so URLs match what we'll write -----
say "Aligning $ENV_FILE with detected values"
TURN_URLS="turn:${DOMAIN}:3478?transport=udp,turn:${DOMAIN}:3478?transport=tcp,turns:${DOMAIN}:5349?transport=tcp"

# Helper: upsert a KEY=VALUE line in .env
upsert_env() {
  local key="$1" val="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    # Use a different delimiter for sed because val may contain commas/colons.
    sed -i "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
  else
    echo "${key}=${val}" >> "$ENV_FILE"
  fi
}

upsert_env TURN_HOST     "$DOMAIN"
upsert_env TURN_USERNAME "$TURN_USERNAME"
upsert_env TURN_PASSWORD "$TURN_PASSWORD"
upsert_env TURN_URLS     "$TURN_URLS"
# Keep legacy vars in sync so config.js's fallback path stays consistent.
upsert_env EXPRESSTURN_USERNAME "$TURN_USERNAME"
upsert_env EXPRESSTURN_PASSWORD "$TURN_PASSWORD"
upsert_env EXPRESSTURN_URLS     "$TURN_URLS"

# ----- 4. Write a clean /etc/turnserver.conf -----
say "Writing /etc/turnserver.conf"
HAS_CERT=0
if [ -d "/etc/letsencrypt/live/${DOMAIN}" ] \
    && [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
  HAS_CERT=1
fi

cat > /etc/turnserver.conf <<EOF
# Generated by fix-voice.sh — coturn for ${DOMAIN}

# --- Listening ports ---
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0

# --- Public IP (server's external address) ---
external-ip=${EXTERNAL_IP}

# --- Realm ---
realm=${DOMAIN}

# --- Long-term credentials (must match server/.env) ---
lt-cred-mech
user=${TURN_USERNAME}:${TURN_PASSWORD}

# --- Relay port range (must be open in firewall) ---
min-port=49152
max-port=65535

# --- Logging ---
log-file=/var/log/turnserver.log
simple-log

# --- Security: block relay to private/internal networks ---
no-multicast-peers
no-loopback-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

# --- Performance ---
total-quota=100
stale-nonce=600
fingerprint
no-tlsv1
no-tlsv1_1
no-cli

EOF

if [ "$HAS_CERT" = "1" ]; then
  cat >> /etc/turnserver.conf <<EOF
# --- TLS for TURNS (port 5349) ---
cert=/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
pkey=/etc/letsencrypt/live/${DOMAIN}/privkey.pem
EOF
  ok "Found Let's Encrypt cert — TURNS (5349) enabled"
else
  warn "No Let's Encrypt cert at /etc/letsencrypt/live/${DOMAIN}/ — TURNS disabled. UDP/TCP TURN still works."
fi

# Enable the daemon (Debian/Ubuntu disables it by default)
if [ -f /etc/default/coturn ]; then
  if grep -q '^#TURNSERVER_ENABLED=1' /etc/default/coturn; then
    sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
  fi
  if ! grep -q '^TURNSERVER_ENABLED=1' /etc/default/coturn; then
    echo 'TURNSERVER_ENABLED=1' >> /etc/default/coturn
  fi
fi

# ----- 5. Open firewall ports -----
say "Opening firewall ports (UFW)"
if command -v ufw >/dev/null; then
  ufw allow 3478/udp        >/dev/null 2>&1 || true
  ufw allow 3478/tcp        >/dev/null 2>&1 || true
  ufw allow 5349/udp        >/dev/null 2>&1 || true
  ufw allow 5349/tcp        >/dev/null 2>&1 || true
  ufw allow 49152:65535/udp >/dev/null 2>&1 || true
  ok "UFW rules added: 3478, 5349, 49152-65535/udp"
else
  warn "UFW not installed — please open these ports yourself: 3478/{udp,tcp}, 5349/{udp,tcp}, 49152-65535/udp"
fi

# ----- 6. Restart services -----
say "Restarting coturn"
systemctl enable coturn >/dev/null 2>&1 || true
systemctl restart coturn

sleep 2
if systemctl is-active --quiet coturn; then
  ok "coturn is running"
else
  warn "coturn failed to start. Check: journalctl -u coturn -n 50"
  systemctl status coturn --no-pager | tail -20
fi

say "Restarting orblood backend"
systemctl restart orblood
sleep 2
if systemctl is-active --quiet orblood; then
  ok "orblood backend is running"
else
  warn "orblood backend failed to start. Check: journalctl -u orblood -n 50"
fi

# ----- 7. Verify -----
say "Verifying coturn is listening on UDP 3478"
if command -v ss >/dev/null && ss -lun | grep -q ':3478 '; then
  ok "coturn is listening on UDP 3478"
else
  warn "Nothing listening on UDP 3478. Check: journalctl -u coturn -n 30"
fi

say "Verifying coturn is listening on TCP 3478"
if command -v ss >/dev/null && ss -ltn | grep -q ':3478 '; then
  ok "coturn is listening on TCP 3478"
else
  warn "Nothing listening on TCP 3478"
fi

say "Verifying API returns ICE servers"
if curl -fsSL --max-time 5 "http://127.0.0.1:4000/api/healthz" >/dev/null 2>&1; then
  ok "Backend API is healthy"
else
  warn "Backend API not responding on :4000"
fi

# ----- 8. Summary -----
say "All done"
cat <<EOF

  External IP:    ${EXTERNAL_IP}
  Domain:         ${DOMAIN}
  TURN URLs:      ${TURN_URLS}
  TURN user:      ${TURN_USERNAME}
  TURN pass:      ${TURN_PASSWORD}

  Test from outside the server:
    https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
    Add server: turn:${DOMAIN}:3478
    Username: ${TURN_USERNAME}
    Password: ${TURN_PASSWORD}
    Click "Add Server", then "Gather candidates"
    You should see a candidate of type "relay" — that proves TURN works.

  If users still can't connect, run:
    journalctl -u coturn -f          # watch coturn live
    tail -f /var/log/turnserver.log  # detailed coturn log

EOF
